// Tree GPU-driven instancing VS:
// Uses visible-index indirection generated by TreeFrustumHiZCull_CS.
//
// Root:
// - b0 (space0): SceneCB
// - t0 (space1): StructuredBuffer<InstanceData> (all instances)
// - t1 (space1): StructuredBuffer<uint> visible indices for this (species,lod,part) batch
// - b2 (space1): root constants (VisibleBase; others unused)

cbuffer SceneCB : register(b0)
{
    matrix View;
    matrix Proj;
    float4 CameraWorld;
};

cbuffer TreeVisibleCB : register(b2, space1)
{
    uint u0, u1, u2, u3, u4, u5, u6, u7;
};
static const uint VisibleBase = u0;

struct InstanceData
{
    matrix World;
    float4 NprPerMesh;
};

StructuredBuffer<InstanceData> gInstanceData : register(t0, space1);
StructuredBuffer<uint> gVisibleIndex : register(t1, space1);

struct VSInput
{
    float3 pos : POSITION;
    float4 color : COLOR;
    float2 uv : TEXCOORD;
    float3 normal : NORMAL;
    float3 tangent : TANGENT;
};

struct VSOutput
{
    float4 svpos : SV_POSITION;
    float4 color : COLOR;
    float2 uv : TEXCOORD;
    float3 normal : NORMAL;
    float3 tangent : TANGENT;
    float3 worldPos : TEXCOORD1;
    float4 nprPerMesh : TEXCOORD2;
};

VSOutput vert(VSInput input, uint instanceID : SV_InstanceID)
{
    VSOutput output;

    const uint instanceIndex = gVisibleIndex[instanceID] + u0;
    matrix worldM = gInstanceData[instanceIndex].World;
    output.nprPerMesh = gInstanceData[instanceIndex].NprPerMesh;

    float4 worldPos = mul(float4(input.pos, 1.0f), worldM);
    float4 viewPos = mul(worldPos, View);
    output.svpos = mul(viewPos, Proj);

    float4 c = input.color;
    if ((abs(c.r) + abs(c.g) + abs(c.b)) < 1e-4f)
        c.rgb = float3(1.0f, 1.0f, 1.0f);
    output.color = c;
    output.uv = input.uv;

    float3 n = (length(input.normal) > 0.1) ? input.normal : float3(0, 0, 1);
    float3 t = (length(input.tangent) > 0.1) ? input.tangent : float3(1, 0, 0);

    output.normal = normalize(mul(n, (float3x3)worldM));
    output.tangent = normalize(mul(t, (float3x3)worldM));
    output.worldPos = worldPos.xyz;
    return output;
}

